name: mayfair
description: App for the Mayfair church

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.3
  google_sign_in: ^4.0.1+1
  flutter_facebook_login: ^2.0.0
  provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/google-logo.png
   - images/facebook-logo.png
